=== poszetkristof/webtechnologiak/lab3/02-menu/menu.dtd
<!-- Egy menüben almenü, menüpont és elválasztó lehet, akárhány, bármilyen sorrendben.
     A | jelenti a választást (ez vagy az), a * az ismétlést (akárhányszor, akár egyszer sem).
     A menu a saját tartalmában is szerepel, ezért lehet a menürendszer tetszőlegesen mély.
 -->
<!ELEMENT menu (menu|item|separator)*>

<!-- A menü neve, pl. "File". Bármilyen szöveg lehet, és kötelező megadni. -->
<!ATTLIST menu
    name CDATA #REQUIRED>

<!-- A menüpontnak nincs tartalma, minden információ a nevében van -->
<!ELEMENT item EMPTY>

<!-- A menüpont neve, pl. "Save as" (szóközzel együtt, ezért CDATA) -->
<!ATTLIST item
    name CDATA #REQUIRED>

<!-- Az elválasztó vonal. Se tartalma, se attribútuma: a puszta létezése hordozza az információt. -->
<!ELEMENT separator EMPTY>

=== poszetkristof/webtechnologiak/lab3/02-menu/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu SYSTEM "menu.dtd">

<menu name="Main">
    <menu name="File">
        <menu name="New">
            <item name="XML" />
            <item name="JSON" />
            <item name="Text" />
        </menu>
        <item name="Open" />
        <item name="Save" />
        <item name="Save as" />
        <separator />
        <item name="Exit" />
    </menu>
    <menu name="Edit">
        <item name="Undo" />
        <item name="Redo" />
        <separator />
        <item name="Cut" />
        <item name="Copy" />
        <item name="Paste" />
    </menu>
    <menu name="Help">
        <item name="About" />
    </menu>
</menu>
